### PR TITLE
Create LICENSE

### PR DESCRIPTION
**Pull request by cthoyt**
This pull request is part of an initiative to make the licensing information about OBO Foundry ontologies more actionable.

While this ontology contains licensing information in its metadata, GitHub is not aware of the license unless you create a `LICENSE` file with standardized text. This PR creates a `LICENSE` file with the standard text for the CC BY 4.0 license. 

More information about this initiative and further discussion is taking place here: https://github.com/OBOFoundry/OBOFoundry.github.io/issues/1840.

### CODE REVIEW

**Comment by egonw** [comment]
The paper writes: `More details, together with a downloadable OWL file, are available at http://code.google.com/p/semanticchemistry/ (license: CC-BY-SA).` So, I will close this PR and add the proper LICENSE file now. Thanks for letting me know it was missing.

**Comment by cthoyt** [comment]
Note that https://obofoundry.org/ontology/cheminf says that the license is CC-BY 4.0 and that the SA clause means that it doesn't quality to be in OBO Foundry based on OBO Principle 001 (https://obofoundry.org/principles/fp-001-open.html). Is there a reason you can't make it more permissive?

**Comment by egonw** [comment]
Interesting. I need to dig up history. Maybe we did change since the article.

For the license change, I need to get permission from all past contributors.

**Comment by cthoyt** [comment]
The CC BY 4.0 annotation was introduced by @rvita in https://github.com/OBOFoundry/OBOFoundry.github.io/commit/836ce7c3e73518035e32e51a7eae5a88ad065f77

**Pull request closed without merging**
